### ISSUE TITLE
Need error message if fields empty

### ISSUE THREAD

**Issue by ajmarvingomez** [Richmond-Creative-Agency/fieldagent#2]
We need an error message if the First Name, Last Name or Email fields are empty.
Assignees: 
Labels: enhancement
Milestone: 

```
          // TODO: Error message if fields empty
```

https://github.com/Richmond-Creative-Agency/fieldagent/blob/62018c560fc4c9da8d6481ae07469ee3df0008a1/src/app/tool/canvassr/CanvassForm.jsx#L77

**Comment by ADTmux** [comment]
Hey, PR https://github.com/Richmond-Creative-Agency/fieldagent/pull/17 is live.
