### ISSUE TITLE
Add all states

### ISSUE THREAD

**Issue by ajmarvingomez** [Richmond-Creative-Agency/fieldagent#4]
Right now we only have one state for Canvassr - VA.

Assignees: 
Labels: enhancement
Milestone: 

https://github.com/Richmond-Creative-Agency/fieldagent/blob/efb7bba0694ff8d3313c01ca6f1b57e80c5ade5f/src/app/tool/canvassr/CanvassForm.jsx#L62

**Comment by ADTmux** [comment]
Hey, PR is live https://github.com/Richmond-Creative-Agency/fieldagent/pull/11
