### ISSUE TITLE
Refactor clearInputs Function

### ISSUE THREAD

**Issue by ajmarvingomez** [Richmond-Creative-Agency/fieldagent#5]
The clearInputs function can be refactored to use all fields in the canvass
Entry Form

Assignees: Labels: enhancement Milestone:

```
  // TODO: Refactor ClearInputs Function
```

https://github.com/Richmond-Creative-Agency/fieldagent/blob/efb7bba0694ff8d3313c01ca6f1b57e80c5ade5f/src/app/tool/canvassr/CanvassForm.jsx#L16

**Comment by amitdave222** [comment]
Hey, PR is live https://github.com/Richmond-Creative-Agency/fieldagent/pull/10
